"""add container tracking columns

Revision ID: 39e4e92771db
Revises: c4c0f3279219
Create Date: 2026-03-09 23:56:36.066870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e4e92771db'
down_revision: Union[str, Sequence[str], None] = 'c4c0f3279219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('container_id', sa.String(length=64), nullable=True))
    op.add_column('businesses', sa.Column('container_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'container_port')
    op.drop_column('businesses', 'container_id')
    # ### end Alembic commands ###
