"""add failed_webhooks table

Revision ID: 7f836a334f01
Revises: b7e3f8a91c42
Create Date: 2026-03-29 09:43:11.236711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f836a334f01'
down_revision: Union[str, Sequence[str], None] = 'b7e3f8a91c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_webhooks_next_retry_at'), 'failed_webhooks', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_failed_webhooks_resolved'), 'failed_webhooks', ['resolved'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('support_tier', sa.String(length=50), nullable=False),
    sa.Column('response_sla_hours', sa.Integer(), nullable=False),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_business_id'), 'support_tickets', ['business_id'], unique=False)
    op.create_table('content_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_performance_content_id'), 'content_performance', ['content_id'], unique=False)
    op.create_index(op.f('ix_activity_cycle_id'), 'activity', ['cycle_id'], unique=False)
    op.add_column('businesses', sa.Column('password_hash', sa.String(length=512), nullable=True))
    op.add_column('businesses', sa.Column('stripe_connect_id', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('stripe_connect_onboarded', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_content_content_type'), 'content', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_status'), 'content', ['status'], unique=False)
    op.create_index(op.f('ix_metrics_name'), 'metrics', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_name'), table_name='metrics')
    op.drop_index(op.f('ix_content_status'), table_name='content')
    op.drop_index(op.f('ix_content_content_type'), table_name='content')
    op.drop_column('businesses', 'stripe_connect_onboarded')
    op.drop_column('businesses', 'stripe_connect_id')
    op.drop_column('businesses', 'password_hash')
    op.drop_index(op.f('ix_activity_cycle_id'), table_name='activity')
    op.drop_index(op.f('ix_content_performance_content_id'), table_name='content_performance')
    op.drop_table('content_performance')
    op.drop_index(op.f('ix_support_tickets_business_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_failed_webhooks_resolved'), table_name='failed_webhooks')
    op.drop_index(op.f('ix_failed_webhooks_next_retry_at'), table_name='failed_webhooks')
    op.drop_table('failed_webhooks')
    # ### end Alembic commands ###
